### ISSUE TITLE
Problem while running the server

### ISSUE THREAD

**Issue by yeabsira-gashaw** [YegnaMart/API#3]
Dear, I am facing difficulty while running the server from the root folder by `npm run server`. But I am facing this error:   `Error: Cannot find module './mongodb_aws'`.

Thank You`

**Comment by Yonas21** [comment]
It's incompatibility in version of Your mongoDB please check Your version and update it and also mongoose from package.json

**Comment by Misganaw-K** [comment]
This error may be because of your mongoose version and node.js version so you should check and update it.

**Comment by yeabsira-gashaw** [comment]
As you have mentioned, the problem was the MongoDB version I have. It is a compatibility issue. Please include the environment specification in the ReadMe file. 

Thank You

**Comment by Yonas21** [comment]
please see the package.json file in dev-yon branch and check version difference between MongoDB 3.4.9 community edition and Your version. and get back at me if there is any problem raised again, about the server see .env file the environment setup about the server and to see how run see package.json script tag
